### ISSUE TITLE
General security review

### ISSUE THREAD

**Issue by shawnadelic** [hackforla/spare#148]
We should spend some time doing a general security review--making sure there aren't any potential vulnerabilities, especially anything that could compromise any of our users' personal info.

**Comment by ndanielsen** [comment]
Just saw this warning:

WARNINGS:
?: (security.W009) Your SECRET_KEY has less than 50 characters or less than 5 unique characters. Please generate a long and random SECRET_KEY, otherwise many of Django's security-critical features will be vulnerable to attack.

For the prod environment, please be sure to generate a secret key this way and keep it secret =)
`docker-compose run server python manage.py generate_secret_key`

**Comment by calexity** [comment]
@shawnadelic I removed the "beta launch" label as beta has launched. I tagged the remaining tickets (like this one) with Version 1.1 milestone
